# Generated by Django 6.0.1 on 2026-01-24 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step", models.IntegerField()),
                ("amount", models.FloatField()),
                ("oldbalanceOrg", models.FloatField()),
                ("newbalanceOrig", models.FloatField()),
                ("oldbalanceDest", models.FloatField()),
                ("newbalanceDest", models.FloatField()),
                ("type_CASH_OUT", models.BooleanField()),
                ("type_DEBIT", models.BooleanField()),
                ("type_PAYMENT", models.BooleanField()),
                ("type_TRANSFER", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stage1_probability", models.FloatField(blank=True, null=True)),
                ("stage2_probability", models.FloatField(blank=True, null=True)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("APPROVE", "APPROVE"),
                            ("REVIEW", "REVIEW"),
                            ("BLOCK", "BLOCK"),
                        ],
                        max_length=10,
                    ),
                ),
                ("stage", models.CharField(max_length=20)),
                ("reason", models.TextField()),
                ("model_version", models.CharField(default="v1.0", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.transaction",
                    ),
                ),
            ],
        ),
    ]
